name: thief-shadows # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Thief Shadows Tactics
summary: Steal treasures with precision!
description: Sneak past guards, steal treasures, and execute flawless heists in risky missions.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  thief-shadows:
    command: bin/thief-shadows-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  thief-shadows:
    plugin: dump
    source: .
    organize:
      thief-shadows-bin: bin/
